### ISSUE TITLE
Language switch during poll creation, returns you to /#/create

### ISSUE THREAD

**Issue by xshadow** [jelhan/croodle#53] opened 2014-11-27 17:53 UTC
You can't switch the languages on - you are returned to https://croodle.jhanschke.de/#/create: 
	- /#/create/meta
	- /#/create/options
	- /#/create/settings

All the things you have done are screwed/gone.

**Comment by jelhan** [comment] 2015-01-20 11:55
The addon used for i18n [ember-i18n](https://github.com/jamesarosen/ember-i18n) does not support binding of translations. Therefore a full page reload is needed to update translations. This is one of the many issues caused by this limitation.

There is an [ongoing discussion](https://github.com/jamesarosen/ember-i18n/issues/132) about supporting bindings in ember-i18n. It's not clear yet if it will be added.

But there are new ember-cli addons for i18n. [ember-cli-i18n](https://github.com/dockyard/ember-cli-i18n) seems to be the most auspicious one. But it's not stable yet and doesn't support ember 1.8. Sould keep an eye on development and consider moving to it in future.

**Comment by jelhan** [comment] 2015-11-24 09:55
Fixed by upgrade of ember-i18n to > 4.0 which observes locale changes. c1dfa16eed49df4423e139170f7ca83d6be378cc and some afterwards

**Closed by jelhan** 2015-11-24 09:55 UTC
Labels: bug
